spring:
  datasource:
    url: jdbc:postgresql://ep-noisy-truth-a8tqg0go.eastus2.azure.neon.tech/courseManagementService
    username: userManagement_owner
    password: YPBSExVb04Ay
    driver-class-name: org.postgresql.Driver
  application:
    name: courseManagementService
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true